openapi: 3.0.1
info:
  title: Swagger Petstore
  description:
    "This is a sample server Petstore server.  You can find out more about\
    \     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net,\
    \ #swagger](http://swagger.io/irc/).      For this sample, you can use the api\
    \ key `special-key` to test the authorization     filters."
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore.swagger.io/v2
  - url: http://petstore.swagger.io/v2
tags:
  - name: task
    description: Everything about your Task
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /task:
    get:
      tags:
        - task
      summary: Finds Pets by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findTask
      responses:
        "200":
          description: successful operation
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
        "400":
          description: Invalid status value
          content: {}
      security:
        - petstore_auth:
            - write:tasks
            - read:tasks
components:
  schemas:
    Task:
      required:
        - title
        - description
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          example: Task 1
        description:
          type: string
          example: Description task
        state:
          type: boolea
          description: task status in the store
          enum:
            - pending
            - completed
      xml:
        name: Task
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  
x-original-swagger-version: "2.0"